"""empty message

Revision ID: 136c508cebb0
Revises: a2b502bb8c6a
Create Date: 2022-03-11 10:27:56.642190

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '136c508cebb0'
down_revision = 'a2b502bb8c6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('proposals', 'call_id',
               existing_type=postgresql.UUID(),
               nullable=True)
    op.alter_column('proposals', 'provider_id',
               existing_type=postgresql.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('proposals', 'provider_id',
               existing_type=postgresql.UUID(),
               nullable=False)
    op.alter_column('proposals', 'call_id',
               existing_type=postgresql.UUID(),
               nullable=False)
    # ### end Alembic commands ###
