"""empty message

Revision ID: 368a7326fb3c
Revises: 
Create Date: 2022-03-07 12:37:25.313179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '368a7326fb3c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('companies', 'password_hash',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint('companies_email_key', 'companies', type_='unique')
    op.drop_constraint('companies_name_key', 'companies', type_='unique')
    op.create_unique_constraint(None, 'companies', ['cnpj'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'companies', type_='unique')
    op.create_unique_constraint('companies_name_key', 'companies', ['name'])
    op.create_unique_constraint('companies_email_key', 'companies', ['email'])
    op.alter_column('companies', 'password_hash',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
