"""empty message

Revision ID: 415ce01cbd05
Revises: c9ae3bc6f997
Create Date: 2022-03-07 23:26:59.157731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "415ce01cbd05"
down_revision = "c9ae3bc6f997"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "companies", "password_hash", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column(
        "employees", "password_hash", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column(
        "providers",
        "password_hash",
        existing_type=sa.VARCHAR(length=511),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "providers",
        "password_hash",
        existing_type=sa.VARCHAR(length=511),
        nullable=True,
    )
    op.alter_column(
        "employees", "password_hash", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column(
        "companies", "password_hash", existing_type=sa.VARCHAR(), nullable=True
    )
    # ### end Alembic commands ###
