"""empty message

Revision ID: 4812fc0f7116
Revises: f8e93531a4dd
Create Date: 2022-03-07 22:25:50.150024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4812fc0f7116'
down_revision = 'f8e93531a4dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('companies', 'password_hash',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint('companies_email_key', 'companies', type_='unique')
    op.drop_constraint('companies_name_key', 'companies', type_='unique')
    op.create_unique_constraint(None, 'companies', ['cnpj'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'companies', type_='unique')
    op.create_unique_constraint('companies_name_key', 'companies', ['name'])
    op.create_unique_constraint('companies_email_key', 'companies', ['email'])
    op.alter_column('companies', 'password_hash',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
