"""empty message

Revision ID: a2b502bb8c6a
Revises: f8e93531a4dd
Create Date: 2022-03-10 21:35:49.220897

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a2b502bb8c6a'
down_revision = 'f8e93531a4dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('calls', 'category_id',
               existing_type=postgresql.UUID(),
               nullable=True)
    op.alter_column('calls', 'subcategory_id',
               existing_type=postgresql.UUID(),
               nullable=True)
    op.alter_column('calls', 'employee_id',
               existing_type=postgresql.UUID(),
               nullable=True)
    op.alter_column('calls', 'selected_proposal_id',
               existing_type=postgresql.UUID(),
               nullable=True)
    op.add_column('companies', sa.Column('type', sa.String(), nullable=True))
    op.alter_column('companies', 'password_hash',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint('companies_name_key', 'companies', type_='unique')
    op.create_unique_constraint(None, 'companies', ['cnpj'])
    op.add_column('employees', sa.Column('type', sa.String(), nullable=True))
    op.alter_column('employees', 'company_id',
               existing_type=postgresql.UUID(),
               nullable=True)
    op.alter_column('employees', 'sector_id',
               existing_type=postgresql.UUID(),
               nullable=True)
    op.alter_column('employees', 'password_hash',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('providers', sa.Column('type', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'providers', ['cnpj'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'providers', type_='unique')
    op.drop_column('providers', 'type')
    op.alter_column('employees', 'password_hash',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('employees', 'sector_id',
               existing_type=postgresql.UUID(),
               nullable=False)
    op.alter_column('employees', 'company_id',
               existing_type=postgresql.UUID(),
               nullable=False)
    op.drop_column('employees', 'type')
    op.drop_constraint(None, 'companies', type_='unique')
    op.create_unique_constraint('companies_name_key', 'companies', ['name'])
    op.alter_column('companies', 'password_hash',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('companies', 'type')
    op.alter_column('calls', 'selected_proposal_id',
               existing_type=postgresql.UUID(),
               nullable=False)
    op.alter_column('calls', 'employee_id',
               existing_type=postgresql.UUID(),
               nullable=False)
    op.alter_column('calls', 'subcategory_id',
               existing_type=postgresql.UUID(),
               nullable=False)
    op.alter_column('calls', 'category_id',
               existing_type=postgresql.UUID(),
               nullable=False)
    # ### end Alembic commands ###
