from app.models.provider_services_model import ProviderServicesModel
from app.models.called_model import CalledModel
from app.models.proposal_model import ProposalModel
from app.models.categorie_model import CategorieModel
from app.models.company_employees_model import CompanyEmployeesModel
from app.models.company_model import CompanyModel
from app.models.provider_costumer_model import ProviderCostumerModel
from app.models.sector_model import SectorModel
from app.models.sub_categorie_model import SubCategorieModel